version: '3'
# define all services
services:
  # our service is called CakePHP ;-)
  cakephp:
    # we want to use the image which is build from our Dockerfile
    build: build/cakephp/
    #context: .
    #dockerfile: CakePHP.Dockerfile
    # apache is running on port 80 but we want to expose this to port 4000 on our local machine
    ports:
      - "8080:80"
    # we are depending on the mysql backend
    depends_on:
      - mysql
    # we mount the working dir into the container, handy for development
    volumes:
      - ./build/cakephp/cakephp:/var/www/html/
    environment:
      - SECURITY_SALT
      - MYSQL_HOST=mysql
      - MYSQL_USERNAME=cakephp
      - MYSQL_PASSWORD=cakephp
  mysql:
    # we use the mysql base image, version 5.6.36
    #image: mysql:5.6.39
    build: build/mysql/
    #context: .
    #dockerfile: MySQL.Dockerfile
    ports:
      - "3306:3006"
    # we mount a datavolume to make sure we don't lose data
    volumes:
      - mysql_data:/var/lib/mysql
    # setting some envvars to create the DB
    environment:
      - MYSQL_ROOT_PASSWORD=cakephp
      - MYSQL_DATABASE=cakephp
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
     - PMA_ARBITRARY=1
     - MYSQL_ROOT_PASSWORD=cakephp
    restart: always
    ports:
     - 8081:80
    volumes:
     - /sessions
    
volumes:
  mysql_data: